# Generated by Django 4.2.29 on 2026-04-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
