# Generated by Django 4.2.29 on 2026-04-25 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('catalog', 'Catalog'), ('menu', 'Menu'), ('policy', 'Policy'), ('faq', 'FAQ document'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='businesses.business')),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='embedding',
                field=VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', VectorField(blank=True, dimensions=1536, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='businesses.business')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='businesses.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['business'], name='businesses__busines_853e44_idx'), models.Index(fields=['document'], name='businesses__documen_48a311_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business'], name='businesses__busines_279bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business', 'doc_type'], name='businesses__busines_2c8f94_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business', 'is_active'], name='businesses__busines_06a925_idx'),
        ),
    ]
