# Generated by Django 4.2.29 on 2026-04-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('business', 'Business')], max_length=10)),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=10)),
                ('wa_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='received', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'phone'], name='messaging_m_busines_dcc6b9_idx')],
            },
        ),
    ]
