# Generated by Django 4.2.29 on 2026-04-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversationstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationstate',
            new_name='messaging_c_busines_ee475b_idx',
            old_name='messaging_c_business_8e0b42_idx',
        ),
    ]
